
name: Make TEIs

on:
  schedule:
    - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  download:
    name: make teis
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: |
          python -m pip config set global.break-system-packages true
          pip install -r requirements.txt
      - name: docx to porcessed tei
        run: |
          python scripts/create_and_process_xmls.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: TEI updates